name: Tests & Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
  schedule:
    # Runs every night at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout webserv_tests
        uses: actions/checkout@v7
        with:
          path: webserv_tests

      - name: Checkout webserv
        uses: actions/checkout@v7
        with:
          repository: jovanako/webserv
          token: ${{ secrets.WEBSERV_ACCESS_TOKEN || github.token }}
          path: webserv

      - name: Install gcovr
        run: sudo apt-get update && sudo apt-get install -y gcovr

      - name: Run tests with coverage
        working-directory: webserv_tests
        run: |
          make coverage
          {
            echo "## 📊 Test Coverage"
            echo '```text'
            gcovr --root ../webserv --object-directory .
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Generate HTML coverage report
        if: always()
        working-directory: webserv_tests
        run: |
          mkdir -p coverage_report
          gcovr --root ../webserv --object-directory . --html-details coverage_report/index.html

      - name: Upload HTML coverage report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-html-report
          path: webserv_tests/coverage_report/

